param(
    [Parameter(Mandatory = $true)]
    [string]$TargetPath,

    [string]$ProjectName = "",

    [ValidateSet("Lite", "Standard", "Enterprise")]
    [string]$Mode = "Standard",

    [string[]]$Stacks = @(),

    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "[init] $Message"
}

function Copy-DirectoryContent {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourceDir,

        [Parameter(Mandatory = $true)]
        [string]$DestinationDir,

        [switch]$Overwrite
    )

    if (-not (Test-Path -LiteralPath $SourceDir)) {
        throw "Source directory not found: $SourceDir"
    }

    New-Item -ItemType Directory -Force -Path $DestinationDir | Out-Null

    Get-ChildItem -LiteralPath $SourceDir -Recurse -File | ForEach-Object {
        $relativePath = $_.FullName.Substring($SourceDir.Length).TrimStart('\', '/')
        $destinationFile = Join-Path $DestinationDir $relativePath
        $destinationParent = Split-Path -Parent $destinationFile

        if (-not (Test-Path -LiteralPath $destinationParent)) {
            New-Item -ItemType Directory -Force -Path $destinationParent | Out-Null
        }

        if ((Test-Path -LiteralPath $destinationFile) -and -not $Overwrite) {
            Write-Host "[skip] $relativePath already exists"
            return
        }

        Copy-Item -LiteralPath $_.FullName -Destination $destinationFile -Force:$Overwrite
        Write-Host "[copy] $relativePath"
    }
}

function Write-InitMetadata {
    param(
        [string]$DestinationDir,
        [string]$Name,
        [string]$SelectedMode,
        [string[]]$SelectedStacks
    )

    $metadataFile = Join-Path $DestinationDir ".claude\init.generated.md"
    $stackText = if ($SelectedStacks.Count -gt 0) { $SelectedStacks -join ", " } else { "deferred" }
    $projectText = if ([string]::IsNullOrWhiteSpace($Name)) { "" } else { $Name }

    $lines = @(
        "# Claude Init Metadata",
        "",
        "Generated by scripts/init-project-template.ps1.",
        "",
        "- ProjectName: $projectText",
        "- Mode: $SelectedMode",
        "- Stacks: $stackText",
        "- StackSelection: deferred means no stack was chosen during initialization. This is normal.",
        "",
        "Use this file as Claude Code initialization metadata. Merge real project facts into .codex/project.md, .codex/scope.md, the docs codebase map, the local toolchain check document, and docs/技术选型.md manually or with Claude Code.",
        "",
        "Stack guidance:",
        "- New projects: confirm product shape, users, constraints, risks, and the v0.1.0 closed loop before choosing a stack.",
        "- Existing projects: infer the stack from project files before asking the user technical-stack questions.",
        "- Feature, fix, and refactor work defaults to the existing stack unless the user explicitly asks for migration or architecture change.",
        "",
        "Mode guidance:",
        "- Lite: keep only essential docs and commands for small scripts, tools, and prototypes.",
        "- Standard: default for normal applications, APIs, internal systems, and data projects.",
        "- Enterprise: use full governance for team delivery, production, inherited, regulated, hardware, or high-risk projects.",
        "",
        "Recommended Claude Code startup order:",
        "1. CLAUDE.md",
        "2. .claude/skills/forgekit-project-workflow/SKILL.md",
        "3. project suitability assessment under docs",
        "4. docs codebase map",
        "5. local toolchain check document under docs",
        "6. Codex next-step work order under docs",
        "7. .codex/project.md, .codex/scope.md, .codex/commands.md",
        "8. .codex/stacks/README.md, then related .codex/stacks/<stack>/ only when a stack is confirmed",
        "9. Task-specific governance files",
        "10. For large changes, use governance/large-change-execution.md first",
        "11. For commands, hooks, plugins, or MCP, use governance/team-agent-rollout.md first"
    )

    Set-Content -LiteralPath $metadataFile -Value $lines -Encoding UTF8
    Write-Host "[copy] .claude\init.generated.md"
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$pluginRoot = Split-Path -Parent $scriptRoot
$templateRoot = Join-Path $pluginRoot "assets"
$projectTemplateDir = Join-Path $templateRoot "project-template"
$templatesDir = Join-Path $templateRoot "templates"
$questionnairesDir = Join-Path $templateRoot "questionnaires"
$normalizedStacks = @()
foreach ($stackValue in $Stacks) {
    if ([string]::IsNullOrWhiteSpace($stackValue)) {
        continue
    }
    $stackValue.Split(',') | ForEach-Object {
        $trimmed = $_.Trim()
        if (-not [string]::IsNullOrWhiteSpace($trimmed)) {
            $normalizedStacks += $trimmed
        }
    }
}

$resolvedTarget = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($TargetPath)

Write-Step "target: $resolvedTarget"
Write-Step "base template: $projectTemplateDir"

if (-not (Test-Path -LiteralPath $resolvedTarget)) {
    New-Item -ItemType Directory -Force -Path $resolvedTarget | Out-Null
}

Copy-DirectoryContent -SourceDir $projectTemplateDir -DestinationDir $resolvedTarget -Overwrite:$Force

if (Test-Path -LiteralPath $questionnairesDir) {
    $targetQuestionnaireDir = Join-Path $resolvedTarget ".codex\questionnaires"
    Copy-DirectoryContent -SourceDir $questionnairesDir -DestinationDir $targetQuestionnaireDir -Overwrite:$Force
}

foreach ($stack in $normalizedStacks) {
    if ([string]::IsNullOrWhiteSpace($stack)) {
        continue
    }

    $stackDir = Join-Path $templatesDir $stack
    if (-not (Test-Path -LiteralPath $stackDir)) {
        throw "Unknown stack template: $stack"
    }

    $destinationStackDir = Join-Path $resolvedTarget ".codex\stacks\$stack"
    Write-Step "stack template: $stack"
    Copy-DirectoryContent -SourceDir $stackDir -DestinationDir $destinationStackDir -Overwrite:$Force
}

Write-InitMetadata -DestinationDir $resolvedTarget -Name $ProjectName -SelectedMode $Mode -SelectedStacks $normalizedStacks

Write-Step "done"
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Start Claude Code from CLAUDE.md"
Write-Host "2. Review .claude/skills/forgekit-project-workflow/SKILL.md"
Write-Host "3. Review the project suitability assessment document under docs (Chinese file name)"
Write-Host "4. Review the codebase map document under docs (Chinese file name)"
Write-Host "5. Review the local toolchain check document under docs (Chinese file name)"
Write-Host "6. Review the Codex next-step work order under docs (Chinese file name)"
Write-Host "7. Optionally run scripts/detect-local-toolchain.ps1 and scripts/run-harness-check.ps1"
Write-Host "8. Review .codex/project.md, .codex/scope.md, and .codex/commands.md"
Write-Host "9. Review .codex/stacks/README.md, then related .codex/stacks/<stack> only when a stack is confirmed"
Write-Host "10. Use .codex/questionnaires/ to fill project-specific details"
Write-Host "11. For large changes, use governance/large-change-execution.md first"
