param(
    [Parameter(Mandatory = $true)]
    [string]$TargetPath,

    [string]$ProjectName = "",

    [ValidateSet("Lite", "Standard", "Enterprise")]
    [string]$Mode = "Standard",

    [string[]]$Stacks = @(),

    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "[init] $Message"
}

function Copy-DirectoryContent {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourceDir,

        [Parameter(Mandatory = $true)]
        [string]$DestinationDir,

        [switch]$Overwrite
    )

    if (-not (Test-Path -LiteralPath $SourceDir)) {
        throw "Source directory not found: $SourceDir"
    }

    New-Item -ItemType Directory -Force -Path $DestinationDir | Out-Null

    Get-ChildItem -LiteralPath $SourceDir -Recurse -File | ForEach-Object {
        $relativePath = $_.FullName.Substring($SourceDir.Length).TrimStart('\', '/')
        $destinationFile = Join-Path $DestinationDir $relativePath
        $destinationParent = Split-Path -Parent $destinationFile

        if (-not (Test-Path -LiteralPath $destinationParent)) {
            New-Item -ItemType Directory -Force -Path $destinationParent | Out-Null
        }

        if ((Test-Path -LiteralPath $destinationFile) -and -not $Overwrite) {
            Write-Host "[skip] $relativePath already exists"
            return
        }

        Copy-Item -LiteralPath $_.FullName -Destination $destinationFile -Force:$Overwrite
        Write-Host "[copy] $relativePath"
    }
}

function Write-InitMetadata {
    param(
        [string]$DestinationDir,
        [string]$Name,
        [string]$SelectedMode,
        [string[]]$SelectedStacks
    )

    $metadataFile = Join-Path $DestinationDir ".codex\init.generated.md"
    $stackText = if ($SelectedStacks.Count -gt 0) { $SelectedStacks -join ", " } else { "deferred" }
    $projectText = if ([string]::IsNullOrWhiteSpace($Name)) { "" } else { $Name }

    $lines = @(
        "# Init Metadata",
        "",
        "Generated by scripts/init-project-template.ps1.",
        "",
        "- ProjectName: $projectText",
        "- Mode: $SelectedMode",
        "- Stacks: $stackText",
        "- StackSelection: deferred means no stack was chosen during initialization. This is normal.",
        "",
        "Use this file as initialization metadata. Merge real project facts into .codex/project.md, .codex/scope.md, the docs codebase map, the local toolchain check document, and docs/技术选型.md manually or with Codex.",
        "",
        "Stack guidance:",
        "- New projects: confirm product shape, users, constraints, risks, and the v0.1.0 closed loop before choosing a stack.",
        "- Existing projects: infer the stack from project files before asking the user technical-stack questions.",
        "- Feature, fix, and refactor work defaults to the existing stack unless the user explicitly asks for migration or architecture change.",
        "",
        "Mode guidance:",
        "- Lite: keep only essential docs and commands for small scripts, tools, and prototypes.",
        "- Standard: default for normal applications, APIs, internal systems, and data projects.",
        "- Enterprise: use full governance for team delivery, production, inherited, regulated, hardware, or high-risk projects.",
        "",
        "Recommended Codex startup order:",
        "1. AGENTS.md",
        "2. project suitability assessment under docs",
        "3. docs codebase map",
        "4. local toolchain check document under docs",
        "5. Codex next-step work order under docs",
        "6. .codex/project.md, .codex/scope.md, .codex/commands.md",
        "7. .codex/stacks/README.md, then related .codex/stacks/<stack>/ only when a stack is confirmed",
        "8. Task-specific governance files",
        "9. For large changes, use governance/large-change-execution.md first",
        "10. For commands, hooks, plugins, or MCP, use governance/team-agent-rollout.md first"
    )

    Set-Content -LiteralPath $metadataFile -Value $lines -Encoding UTF8
    Write-Host "[copy] .codex\init.generated.md"
}

function Write-ClaudeInitMetadata {
    param(
        [string]$DestinationDir,
        [string]$Name,
        [string]$SelectedMode,
        [string[]]$SelectedStacks
    )

    $metadataFile = Join-Path $DestinationDir ".claude\init.generated.md"
    $stackText = if ($SelectedStacks.Count -gt 0) { $SelectedStacks -join ", " } else { "deferred" }
    $projectText = if ([string]::IsNullOrWhiteSpace($Name)) { "" } else { $Name }

    $lines = @(
        "# Claude Init Metadata",
        "",
        "Generated by scripts/init-project-template.ps1.",
        "",
        "- ProjectName: $projectText",
        "- Mode: $SelectedMode",
        "- Stacks: $stackText",
        "- StackSelection: deferred means no stack was chosen during initialization. This is normal.",
        "",
        "Use this file as Claude Code initialization metadata. Merge real project facts into .codex/project.md, .codex/scope.md, the docs codebase map, the local toolchain check document, and docs/技术选型.md manually or with Claude Code.",
        "",
        "Recommended Claude Code startup order:",
        "1. CLAUDE.md",
        "2. .claude/skills/forgekit-project-workflow/SKILL.md",
        "3. docs codebase map",
        "4. local toolchain check document under docs",
        "5. Codex next-step work order under docs",
        "6. .codex/project.md, .codex/scope.md, .codex/commands.md",
        "7. .codex/stacks/README.md, then related .codex/stacks/<stack>/ only when a stack is confirmed",
        "8. Task-specific governance files"
    )

    $metadataParent = Split-Path -Parent $metadataFile
    if (-not (Test-Path -LiteralPath $metadataParent)) {
        New-Item -ItemType Directory -Force -Path $metadataParent | Out-Null
    }
    Set-Content -LiteralPath $metadataFile -Value $lines -Encoding UTF8
    Write-Host "[copy] .claude\init.generated.md"
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$templateRoot = Split-Path -Parent $scriptRoot
$projectTemplateDir = Join-Path $templateRoot "project-template"
$templatesDir = Join-Path $templateRoot "templates"
$questionnairesDir = Join-Path $templateRoot "questionnaires"
$normalizedStacks = @()
foreach ($stackValue in $Stacks) {
    if ([string]::IsNullOrWhiteSpace($stackValue)) {
        continue
    }
    $stackValue.Split(',') | ForEach-Object {
        $trimmed = $_.Trim()
        if (-not [string]::IsNullOrWhiteSpace($trimmed)) {
            $normalizedStacks += $trimmed
        }
    }
}

$resolvedTarget = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($TargetPath)

Write-Step "target: $resolvedTarget"
Write-Step "base template: $projectTemplateDir"

if (-not (Test-Path -LiteralPath $resolvedTarget)) {
    New-Item -ItemType Directory -Force -Path $resolvedTarget | Out-Null
}

Copy-DirectoryContent -SourceDir $projectTemplateDir -DestinationDir $resolvedTarget -Overwrite:$Force

if (Test-Path -LiteralPath $questionnairesDir) {
    $targetQuestionnaireDir = Join-Path $resolvedTarget ".codex\questionnaires"
    Copy-DirectoryContent -SourceDir $questionnairesDir -DestinationDir $targetQuestionnaireDir -Overwrite:$Force
}

foreach ($stack in $normalizedStacks) {
    if ([string]::IsNullOrWhiteSpace($stack)) {
        continue
    }

    $stackDir = Join-Path $templatesDir $stack
    if (-not (Test-Path -LiteralPath $stackDir)) {
        throw "Unknown stack template: $stack"
    }

    $destinationStackDir = Join-Path $resolvedTarget ".codex\stacks\$stack"
    Write-Step "stack template: $stack"
    Copy-DirectoryContent -SourceDir $stackDir -DestinationDir $destinationStackDir -Overwrite:$Force
}

Write-InitMetadata -DestinationDir $resolvedTarget -Name $ProjectName -SelectedMode $Mode -SelectedStacks $normalizedStacks
Write-ClaudeInitMetadata -DestinationDir $resolvedTarget -Name $ProjectName -SelectedMode $Mode -SelectedStacks $normalizedStacks

Write-Step "done"
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Enter the generated project:"
Write-Host "   cd $resolvedTarget"
Write-Host "2. Start your AI coding tool from that project:"
Write-Host "   Codex: codex"
Write-Host "   Claude Code: claude"
Write-Host "3. Send the startup message:"
Write-Host "   Codex: Read AGENTS.md and help me initialize this project with ForgeKit."
Write-Host "   Claude Code: Read CLAUDE.md and help me initialize this project with ForgeKit."
Write-Host ""
Write-Host "Do not choose a tech stack here. ForgeKit will confirm or infer it during the discovery interview."
