#!/usr/bin/env bash
set -euo pipefail

target_path=""
project_name=""
mode="Standard"
force=0
stacks=()

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/init-project-template.sh --target-path /path/to/project --project-name my-app [--mode Standard] [--force] [--stacks java-springboot,vue]

Options:
  --target-path PATH     Required. Directory to generate the project template into.
  --project-name NAME    Optional project name written into init metadata.
  --mode MODE            Lite, Standard, or Enterprise. Default: Standard.
  --stacks LIST          Optional comma-separated stack templates to copy.
  --force                Overwrite existing files.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-path)
      target_path="${2:-}"
      shift 2
      ;;
    --project-name)
      project_name="${2:-}"
      shift 2
      ;;
    --mode)
      mode="${2:-Standard}"
      shift 2
      ;;
    --stacks)
      IFS=',' read -r -a stacks <<< "${2:-}"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$target_path" ]]; then
  echo "Missing required --target-path" >&2
  usage >&2
  exit 1
fi

case "$mode" in
  Lite|Standard|Enterprise) ;;
  *)
    echo "Invalid --mode: $mode. Expected Lite, Standard, or Enterprise." >&2
    exit 1
    ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
project_template_dir="$repo_root/project-template"
templates_dir="$repo_root/templates"
questionnaires_dir="$repo_root/questionnaires"
resolved_target="$(mkdir -p "$target_path" && cd "$target_path" && pwd)"

copy_tree() {
  local source_dir="$1"
  local destination_dir="$2"

  if [[ ! -d "$source_dir" ]]; then
    echo "Source directory not found: $source_dir" >&2
    exit 1
  fi

  mkdir -p "$destination_dir"
  while IFS= read -r -d '' source_file; do
    local relative_path="${source_file#"$source_dir"/}"
    local destination_file="$destination_dir/$relative_path"
    mkdir -p "$(dirname "$destination_file")"

    if [[ -e "$destination_file" && "$force" -ne 1 ]]; then
      echo "[skip] $relative_path already exists"
      continue
    fi

    cp -f "$source_file" "$destination_file"
    echo "[copy] $relative_path"
  done < <(find "$source_dir" -type f -print0)
}

write_codex_metadata() {
  local metadata_file="$resolved_target/.codex/init.generated.md"
  local stack_text="deferred"
  if [[ ${#stacks[@]} -gt 0 && -n "${stacks[*]// /}" ]]; then
    stack_text="$(IFS=', '; echo "${stacks[*]}")"
  fi

  mkdir -p "$(dirname "$metadata_file")"
  cat > "$metadata_file" <<EOF
# Init Metadata

Generated by scripts/init-project-template.sh.

- ProjectName: $project_name
- Mode: $mode
- Stacks: $stack_text
- StackSelection: deferred means no stack was chosen during initialization. This is normal.

Use this file as initialization metadata. Merge real project facts into .codex/project.md, .codex/scope.md, the docs codebase map, the local toolchain check document, and docs/技术选型.md manually or with Codex.

Stack guidance:
- New projects: confirm product shape, users, constraints, risks, and the v0.1.0 closed loop before choosing a stack.
- Existing projects: infer the stack from project files before asking the user technical-stack questions.
- Feature, fix, and refactor work defaults to the existing stack unless the user explicitly asks for migration or architecture change.

Mode guidance:
- Lite: keep only essential docs and commands for small scripts, tools, and prototypes.
- Standard: default for normal applications, APIs, internal systems, and data projects.
- Enterprise: use full governance for team delivery, production, inherited, regulated, hardware, or high-risk projects.
EOF
  echo "[copy] .codex/init.generated.md"
}

write_claude_metadata() {
  local metadata_file="$resolved_target/.claude/init.generated.md"
  local stack_text="deferred"
  if [[ ${#stacks[@]} -gt 0 && -n "${stacks[*]// /}" ]]; then
    stack_text="$(IFS=', '; echo "${stacks[*]}")"
  fi

  mkdir -p "$(dirname "$metadata_file")"
  cat > "$metadata_file" <<EOF
# Claude Init Metadata

Generated by scripts/init-project-template.sh.

- ProjectName: $project_name
- Mode: $mode
- Stacks: $stack_text
- StackSelection: deferred means no stack was chosen during initialization. This is normal.

Use this file as Claude Code initialization metadata. Merge real project facts into .codex/project.md, .codex/scope.md, the docs codebase map, the local toolchain check document, and docs/技术选型.md manually or with Claude Code.

Recommended Claude Code startup order:
1. CLAUDE.md
2. .claude/skills/forgekit-project-workflow/SKILL.md
3. docs codebase map
4. local toolchain check document under docs
5. Codex next-step work order under docs
6. .codex/project.md, .codex/scope.md, .codex/commands.md
7. .codex/stacks/README.md, then related .codex/stacks/<stack>/ only when a stack is confirmed
8. Task-specific governance files
EOF
  echo "[copy] .claude/init.generated.md"
}

echo "[init] target: $resolved_target"
echo "[init] base template: $project_template_dir"

copy_tree "$project_template_dir" "$resolved_target"

if [[ -d "$questionnaires_dir" ]]; then
  copy_tree "$questionnaires_dir" "$resolved_target/.codex/questionnaires"
fi

for stack in "${stacks[@]}"; do
  stack="$(echo "$stack" | xargs)"
  [[ -z "$stack" ]] && continue
  stack_dir="$templates_dir/$stack"
  if [[ ! -d "$stack_dir" ]]; then
    echo "Unknown stack template: $stack" >&2
    exit 1
  fi
  echo "[init] stack template: $stack"
  copy_tree "$stack_dir" "$resolved_target/.codex/stacks/$stack"
done

write_codex_metadata
write_claude_metadata

echo "[init] done"
echo
echo "Next steps:"
echo "1. Enter the generated project:"
echo "   cd $resolved_target"
echo "2. Start your AI coding tool from that project:"
echo "   Codex: codex"
echo "   Claude Code: claude"
echo "3. Send the startup message:"
echo "   Codex: Read AGENTS.md and help me initialize this project with ForgeKit."
echo "   Claude Code: Read CLAUDE.md and help me initialize this project with ForgeKit."
echo
echo "Do not choose a tech stack here. ForgeKit will confirm or infer it during the discovery interview."
