param(
    [Parameter(Mandatory = $true)]
    [string]$TargetPath,

    [string]$ProjectName = "",

    [string[]]$Stacks = @(),

    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "[init] $Message"
}

function Copy-DirectoryContent {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourceDir,

        [Parameter(Mandatory = $true)]
        [string]$DestinationDir,

        [switch]$Overwrite
    )

    if (-not (Test-Path -LiteralPath $SourceDir)) {
        throw "Source directory not found: $SourceDir"
    }

    New-Item -ItemType Directory -Force -Path $DestinationDir | Out-Null

    Get-ChildItem -LiteralPath $SourceDir -Recurse -File | ForEach-Object {
        $relativePath = $_.FullName.Substring($SourceDir.Length).TrimStart('\', '/')
        $destinationFile = Join-Path $DestinationDir $relativePath
        $destinationParent = Split-Path -Parent $destinationFile

        if (-not (Test-Path -LiteralPath $destinationParent)) {
            New-Item -ItemType Directory -Force -Path $destinationParent | Out-Null
        }

        if ((Test-Path -LiteralPath $destinationFile) -and -not $Overwrite) {
            Write-Host "[skip] $relativePath already exists"
            return
        }

        Copy-Item -LiteralPath $_.FullName -Destination $destinationFile -Force:$Overwrite
        Write-Host "[copy] $relativePath"
    }
}

function Write-InitMetadata {
    param(
        [string]$DestinationDir,
        [string]$Name,
        [string[]]$SelectedStacks
    )

    $metadataFile = Join-Path $DestinationDir ".codex\init.generated.md"
    $stackText = if ($SelectedStacks.Count -gt 0) { $SelectedStacks -join ", " } else { "" }
    $projectText = if ([string]::IsNullOrWhiteSpace($Name)) { "" } else { $Name }

    $lines = @(
        "# Init Metadata",
        "",
        "Generated by scripts/init-project-template.ps1.",
        "",
        "- ProjectName: $projectText",
        "- Stacks: $stackText",
        "",
        "Use this file as initialization metadata. Merge real project facts into .codex/project.md and docs/technology-selection manually or with Codex."
    )

    Set-Content -LiteralPath $metadataFile -Value $lines -Encoding UTF8
    Write-Host "[copy] .codex\init.generated.md"
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$templateRoot = Split-Path -Parent $scriptRoot
$projectTemplateDir = Join-Path $templateRoot "project-template"
$templatesDir = Join-Path $templateRoot "templates"
$questionnairesDir = Join-Path $templateRoot "questionnaires"
$normalizedStacks = @()
foreach ($stackValue in $Stacks) {
    if ([string]::IsNullOrWhiteSpace($stackValue)) {
        continue
    }
    $stackValue.Split(',') | ForEach-Object {
        $trimmed = $_.Trim()
        if (-not [string]::IsNullOrWhiteSpace($trimmed)) {
            $normalizedStacks += $trimmed
        }
    }
}

$resolvedTarget = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($TargetPath)

Write-Step "target: $resolvedTarget"
Write-Step "base template: $projectTemplateDir"

if (-not (Test-Path -LiteralPath $resolvedTarget)) {
    New-Item -ItemType Directory -Force -Path $resolvedTarget | Out-Null
}

Copy-DirectoryContent -SourceDir $projectTemplateDir -DestinationDir $resolvedTarget -Overwrite:$Force

if (Test-Path -LiteralPath $questionnairesDir) {
    $targetQuestionnaireDir = Join-Path $resolvedTarget ".codex\questionnaires"
    Copy-DirectoryContent -SourceDir $questionnairesDir -DestinationDir $targetQuestionnaireDir -Overwrite:$Force
}

foreach ($stack in $normalizedStacks) {
    if ([string]::IsNullOrWhiteSpace($stack)) {
        continue
    }

    $stackDir = Join-Path $templatesDir $stack
    if (-not (Test-Path -LiteralPath $stackDir)) {
        throw "Unknown stack template: $stack"
    }

    $destinationStackDir = Join-Path $resolvedTarget ".codex\stacks\$stack"
    Write-Step "stack template: $stack"
    Copy-DirectoryContent -SourceDir $stackDir -DestinationDir $destinationStackDir -Overwrite:$Force
}

Write-InitMetadata -DestinationDir $resolvedTarget -Name $ProjectName -SelectedStacks $normalizedStacks

Write-Step "done"
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Review .codex/project.md and .codex/scope.md"
Write-Host "2. Review docs/technology-selection document"
Write-Host "3. Use .codex/questionnaires/ to fill project-specific details"
