param(
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

function Test-CommandAvailable {
    param([string]$Name)
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CommandVersion {
    param(
        [string]$Name,
        [string[]]$VersionArguments = @("--version")
    )

    if (-not (Test-CommandAvailable $Name)) {
        return "missing"
    }

    try {
        $output = & $Name @VersionArguments 2>&1 | Select-Object -First 1
        if ([string]::IsNullOrWhiteSpace($output)) {
            return "available"
        }
        return ($output.ToString()).Trim()
    } catch {
        return "available, version check failed"
    }
}

function Add-ToolRow {
    param(
        [System.Collections.Generic.List[string]]$Rows,
        [string]$Tool,
        [string]$Command,
        [string]$Purpose,
        [string[]]$VersionArgs = @("--version")
    )

    $status = if (Test-CommandAvailable $Command) { "available" } else { "missing" }
    $version = Get-CommandVersion -Name $Command -VersionArguments $VersionArgs
    $Rows.Add("| $Tool | ``$Command`` | $Purpose | $status | $version |") | Out-Null
}

$rows = New-Object System.Collections.Generic.List[string]
Add-ToolRow $rows "Git" "git" "version control"
Add-ToolRow $rows "Java" "java" "Java runtime and Spring Boot projects"
Add-ToolRow $rows "Maven" "mvn" "Java build and local tests"
Add-ToolRow $rows "Gradle" "gradle" "Java build and local tests"
Add-ToolRow $rows "Node.js" "node" "frontend and Node services"
Add-ToolRow $rows "npm" "npm" "frontend and Node package scripts"
Add-ToolRow $rows "pnpm" "pnpm" "frontend package scripts"
Add-ToolRow $rows "Python" "python" "Python services and scripts"
Add-ToolRow $rows "pip" "pip" "Python package management"
Add-ToolRow $rows "Docker" "docker" "local services and containers"
Add-ToolRow $rows "Ollama" "ollama" "local LLM endpoint"
Add-ToolRow $rows "Vivado" "vivado" "FPGA project checks"
Add-ToolRow $rows "Vitis HLS" "vitis_hls" "HLS simulation and synthesis"

$languageServerRows = @(
    "| Java LSP | ``jdtls`` | Java symbol search | $(if (Test-CommandAvailable "jdtls") { "available" } else { "missing" }) | optional; IDEA project model is also acceptable |",
    "| TypeScript LSP | ``typescript-language-server`` | TS/JS symbol search | $(if (Test-CommandAvailable "typescript-language-server") { "available" } else { "missing" }) | optional; editor integration is acceptable |",
    "| Vue LSP | ``vue-language-server`` | Vue SFC symbol search | $(if (Test-CommandAvailable "vue-language-server") { "available" } else { "missing" }) | optional |",
    "| Pyright | ``pyright`` | Python symbol and type checks | $(if (Test-CommandAvailable "pyright") { "available" } else { "missing" }) | optional; Pylance is also acceptable |"
)

$report = @(
    "# Local Toolchain Detection",
    "",
    "Generated by ``scripts/detect-local-toolchain.ps1``.",
    "",
    "This report is advisory. Do not install missing tools or start services without user confirmation.",
    "",
    "## Core Tools",
    "",
    "| Tool | Command | Purpose | Status | Version |",
    "| --- | --- | --- | --- | --- |"
) + $rows + @(
    "",
    "## Language / Symbol Tools",
    "",
    "| Tool | Command | Purpose | Status | Notes |",
    "| --- | --- | --- | --- | --- |"
) + $languageServerRows + @(
    "",
    "## Next Steps",
    "",
    "- Copy relevant findings into the local toolchain check document under docs.",
    "- If a required tool is missing, record it as a risk or setup task first.",
    "- Prefer project-local validation commands from ``.codex/commands.md`` over global guesses."
)

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $report
} else {
    $parent = Split-Path -Parent $OutputPath
    if (-not [string]::IsNullOrWhiteSpace($parent) -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    Set-Content -LiteralPath $OutputPath -Value $report -Encoding UTF8
    Write-Host "[ok] wrote $OutputPath"
}
